language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: BVCy9xQFotGMp8RbwgPhSR4yTCGK1KCd+4KRpM1JgXYl754TW5CPyEaUwjVnHqSh3LSiiBZMHAs9rMUSabVZLy9TW7t4Z8EYJbe01Pus/C+4NcVLNjulMqtTYncrA/fvLWFlipyh6CCVpiJfRUvM6VHWhjPdCOqt0bEsHI+m2BweZL0wH3ir+BieHpRXMZ+RoMEl8KF8g6ntKyG5UwJpwkKbUaIDvVYJNqBLZbHRq5Te5O0Mz4YFdwFJBw2dqyBiUO6rmLhhwkMrgUC7Q4f6MqN+vwiblCkU3FV8NL0kKrxzux9JqtY0f5yd5IThhx7nDBb/HSb0dHiSkUrgpapUAPIUvWtwAWZAVTUB5zFtEFkbh5q0XGR3maInSf7X05PYEyC0625aZt5i5er5oAWPNJaa2zBPAIZbroGL7ErLs8w3CO02ySY8powbqYGMaX7reMKvibJFgdtGuja7zEa+Xm6KyAkQrmXzT8daKcRj4bZu2rngArcRBiZr5bEGKxDt+THk3ksw5y5RG368ZB7jmyFU+o5ob+Y026C4GJ/iTw9jjZz8yb8B4ExRR95on3VeAyqPbWFV1epi9ivtOna/1R83oAODKINMa9BBIx3r1XMn2qOUOaxdgEHVAP8sJKcaBE/6zCflutXfuQH3ngANrJ7T7RDN6u7SoRBXd5cxCjQ=
