language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: mmdNhXL8lgmjxmYzXJ9u2EBGo/FkfsKf2ud/uafq36uwDB1p0LXVvU2VLARt6l1qKHZ67ZmtI+k90zP7U62uACTZCrk94krA4W460ZmR27QWbuTmLkyqJG27U+bFs4gD0NhnsAFgTQ6ILjtWje4sGiwDLakYUMqBvCnzf+wtAWxEc9Q0XFMzfm5fyHEXf49/ydQvYpQff3xvWTsfbJH1LT9g7FTfaCrE3j5Ntl8uhnQVP38hY5nOEIlktj7kYvkuhGSj9SiZJcyyl5VPBFVoG/SKpPGBFYOVY6ghwGckHwdTCBkkHFBmUb0f2hHD23sTieETR+3eGEaJGEQ4rYnp/DD4JzY6RzMjJ8PTJb7Ijn/KR5yai6fLemJfHxYEePxJ9+6XpdkjfVaC74ov426R5vEqZLfNYpskajtEl82mpaUZowvCcEAh6GDAuKrtq5gnZ07EF9Oly/QmvYf1fUDtg7HqEpFFSeC7ewLEmst+/6plz+F8SQx/iETBVb9XQGJ/P5A9YMlbBOqBP4TFKxrvDUfIZYMQJWXqTD3SKeyDXx9nw3kloEvuYp7u1fcG9ul1S65103T6pVFqV/LQkA1HX7crGjEI5LW+KDhHzlMRYWpww52ycEqD3NqXJ8D+yAiqbFaCxrCJkXjHrHfMhBXAky6SocDkxlfKsDtYg2UzS+Q=
